### ISSUE TITLE
Incorrect url for oauth token

### ISSUE THREAD

**Issue by fjoenichols** [lostcol0ny/blizzardapi2#12]
**Describe the bug**
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://us.api.blizzard.com/oauth/token?grant_type=client_credentials 

**To Reproduce**
Use the example code with categories index.  

**Expected behavior**
This should return a token which is used in the api calls, not a 404.

**Comment by lostcol0ny** [comment]
You're absolutely right. I'll merge the PR shortly, thanks!
